# Generated by Django 6.0.2 on 2026-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='room_type',
            field=models.CharField(choices=[('PG', 'PG'), ('Flat', 'Flat'), ('Hostel', 'Hostel'), ('Apartment', 'Apartment'), ('Room', 'Room')], max_length=20),
        ),
    ]
