# Generated by Django 6.0.2 on 2026-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_property_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='property',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
