# Generated by Django 6.0.2 on 2026-05-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_inquiry_property_inquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='property',
        ),
    ]
